# fly.toml app configuration file generated for plausible-clickhouse-db on 2025-05-04T14:38:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plausible-clickhouse-db'
primary_region = 'sin'

[build]

[env]
  CLICKHOUSE_SKIP_USER_SETUP="1"

[[mounts]]
  source = 'plausible_clickhouse_data'
  destination = '/var/lib/clickhouse'

[http_service]
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
