# fly.toml app configuration file generated for plausible-postgres-muddy-cherry-4903 on 2025-05-12T12:42:23+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plausible-postgres'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'plausible_postgres_data'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
